#!/usr/bin/env bash

# version
VERSION="0.4.2-noqqe"
# bookmarks file
BOOKMARKS=~/.bookmarks

# Output usage info
#

usage() {
  cat <<EOF

  Usage: bm [options] [cmd]

  Commands:

    # add a bookmark with the given url and optional tags
    $ bm add <url> [tag...]

    # open the first bookmark matching <query>
    $ bm open <query>
    $ bm <query>

    # search the bookmarks via full-text <query>
    $ bm search <query>

    # list tags
    $ bm tags

    # list bookmarks available
    $ bm list
    $ bm ls
    $ bm

    # display statistics about the bookmarks
    $ bm statistics
    $ bm stats

    # clear all bookmarks
    $ bm clear

  Options:

     -V, --version   output bm version
     -h, --help      output this help information

EOF
}

#
# Add a bookmark
#
#   <url> [description] [tag ...]
#

save_bookmark() {
  local url=$1
  local tags=${@:2}
  echo "  Added bookmark"
  echo "    url: $url"
  echo "    tags: $tags"
  echo "$url|$tags" >> $BOOKMARKS
}

#
# List all bookmarks
#

list_bookmarks() {
  echo
  cat $BOOKMARKS \
    | awk '
    BEGIN { FS = "|" }
    {
      printf "* url:\033[1;32m%s\033[0m\n", $1
      printf "  tags: \033[1;37m%s\033[0m\n", $2
    }' \
    | sed 's/http:\/\///'
  echo
}

#
# Search all bookmarks with <query>
#

search_bookmarks() {
  echo "Results for $1:"
  cat $BOOKMARKS \
    | grep $1 \
    | awk '
    BEGIN { FS = "|" }
    {
      printf "* url: \033[1;32m%s\033[0m\n", $1
      printf "  tags: \033[1;37m%s\033[0m\n", $2
    }' \
    | sed 's/http:\/\///'
}

#
# Open first bookmark matching <query>
#

open_bookmark() {
  cat $BOOKMARKS \
    | grep $1 \
    | cut -d '|' -f 1 \
    | xargs open
}

#
# Diplay some statistics about the bookmarks
#

show_statistics() {
  local total_bookmarks=$(cat $BOOKMARKS | wc -l | sed 's/^ *//')
  local total_tags=$(list_tags | wc -l | sed 's/^ *//')
  echo "    total bookmarks: $total_bookmarks"
  echo "         total tags: $total_tags"
  echo "        top 10 tags: `display_top_ten_tags`"
}

#
# Output tags.
#

list_tags() {
  cat $BOOKMARKS \
    | cut -f2 -d '|' \
    | tr " " "\n" \
    | sort \
    | uniq -c \
    | sort -nr
}

#
# Display the 10 most frequently used tags
#

display_top_ten_tags() {
  echo
  printf "%20s  %s\n" count tag
  list_tags \
    | head -10 \
    | awk '{ printf("%20d  %s\n", $1, $2) }'
}

#
# List urls
#

urls() {
  cat $BOOKMARKS \
    | grep "$1" \
    | cut -d '|' -f 1
}


#
# Remove all bookmarks
#

clear_bookmarks() {
  rm $BOOKMARKS
}

# no args

if test $# -eq 0; then
  list_bookmarks
  exit
fi

# parse args

while test $# -ne 0; do
  arg=$1; shift
  case $arg in
    -V|--version) echo $VERSION; exit ;;
    -h|--help) usage; exit ;;
    tags) list_tags; exit ;;
    ls|list) list_bookmarks; exit ;;
    search) search_bookmarks "$@"; exit ;;
    open) open_bookmark "$@"; exit ;;
    add) save_bookmark "$@"; exit ;;
    stats|statistics) show_statistics; exit ;;
    clear) clear_bookmarks; exit ;;
    *) open_bookmark $arg; exit ;;
  esac
done
