#!/usr/bin/env bash

# version
VERSION="0.4.2-noqqe"
# bookmarks file
BOOKMARKS=~/.bookmarks
# push/pull
HOST=""
USER=""
BACKUPDIR="" # Make shure, that this directory exist on your host


# Output usage info
#

usage() {
  cat <<EOF

  Usage: bm [options] [cmd]

  Commands:

    # add a bookmark with the given url and optional tags
    $ bm add <url> [tag...]

    # list bookmarks available
    $ bm list
    $ bm ls
    $ bm
    $ bm 20

    # open the first bookmark matching <query>
    $ bm open <query>

    # search the bookmarks via full-text <query>
    $ bm search <query>

    # list tags
    $ bm tags

    # display statistics about the bookmarks
    $ bm statistics
    $ bm stats

    # sync with host
    # be shure, that you set $HOST, $USER and $BACKUPDIR in script
    # send to host
    $ bm push

    # get from host
    $ bm pull

  Options:

     -V, --version   output bm version
     -h, --help      output this help information

EOF
}

# Add a bookmark
#   <url> [description] [tag ...]

save_bookmark() {
  local url=$1
  local tags=${@:2}
  local date=$(date +%FT%H:%M:%S%z)
  local title=$(curl "$url" -so -|ggrep -iPo '(?<=<title>)(.*)(?=</title>)'|sed 's#|# #g')
  echo "  Added bookmark"
  echo "    title: $title"
  echo "    url: $url"
  echo "    tags: $tags"
  echo "    date: $date"
  echo "$url|$tags|$date|$title" >> $BOOKMARKS
}

# List all bookmarks
#

list_bookmarks() {
  echo
  cat $BOOKMARKS | tail -${1:-10} \
    | awk '
    BEGIN { FS = "|" }
    {
      printf "* title: \033[1;32m%s\033[0m\n", $4
      printf "  url: %s\n", $1
      printf "  tags: \033[1;37m%s\033[0m\n", $2
      printf "  date: %s\n\n", $3
    }'
}

# Search all bookmarks with <query>
#

search_bookmarks() {
  echo "Results for $1:"
  echo
  cat $BOOKMARKS \
    | grep -i $1 \
    | awk '
    BEGIN { FS = "|" }
    {
      printf "* title: \033[1;32m%s\033[0m\n", $4
      printf "  url: %s\n", $1
      printf "  tags: \033[1;37m%s\033[0m\n", $2
      printf "  date: %s\n\n", $3
    }'
}

# Open first bookmark matching <query>
#

open_bookmark() {
  cat $BOOKMARKS \
    | grep $1 \
    | cut -d '|' -f 1 \
    | xargs open
}

# Diplay some statistics about the bookmarks
#

show_statistics() {
  local total_bookmarks=$(cat $BOOKMARKS | wc -l | sed 's/^ *//')
  local total_tags=$(list_tags | wc -l | sed 's/^ *//')
  echo "    total bookmarks: $total_bookmarks"
  echo "         total tags: $total_tags"
  echo "        top 10 tags: `display_top_ten_tags`"
}

# Output tags.
#

list_tags() {
  cat $BOOKMARKS \
    | cut -f2 -d '|' \
    | tr " " "\n" \
    | sort \
    | uniq -c \
    | sort -nr
}

# Display the 10 most frequently used tags
#

display_top_ten_tags() {
  echo
  printf "%20s  %s\n" count tag
  list_tags \
    | head -10 \
    | awk '{ printf("%20d  %s\n", $1, $2) }'
}

# List urls
#

urls() {
  cat $BOOKMARKS \
    | grep "$1" \
    | cut -d '|' -f 1
}

# Push to host
#

push() {
   rsync --numeric-ids -avze ssh ~/.bookmarks $USER@$HOST:$BACKUPDIR
}

# Pull from host
#

pull() {
   rsync -avze ssh $USER@$HOST:$BACKUPDIR/.bookmarks ~/
}


# no args

if test $# -eq 0; then
  list_bookmarks 10
  exit
fi

# parse args

while test $# -ne 0; do
  arg=$1; shift
  case $arg in
    -V|--version) echo $VERSION; exit ;;
    -h|--help) usage; exit ;;
    tags) list_tags; exit ;;
    ls|list) list_bookmarks "$@"; exit ;;
    search) search_bookmarks "$@"; exit ;;
    open) open_bookmark "$@"; exit ;;
    add) save_bookmark "$@"; exit ;;
    stats|statistics) show_statistics; exit ;;
    -ps|push) push; exit;;
    -pl|pull) pull; exit;;
    *) list_bookmarks $arg; exit ;;
  esac
done
